### ISSUE TITLE
Link to the video of the talk

### ISSUE THREAD

**Issue by pabloesm** [higsch/svelte-loves-d3#1]
Hi Matthias,

First of all, thanks for sharing your work, it's really inspiring. 

Since your talk is on Youtube, I'm sure that anyone who comes to this repository would appreciate it if you included the video of the talk as well: 
https://www.youtube.com/watch?v=bnd64ZrHC0U&feature=emb_title

Greetings

**Comment by higsch** [comment]
Thanks! I added it.
