### ISSUE TITLE
Elaboration of your D3+Svelte strategy

### ISSUE THREAD

**Issue by ixxie** [higsch/svelte-loves-d3#2]
Dear Matthias,

I was going to write an email but I couldn't find your address anywhere, and figured why not drop an issue, as this is quasirelated to this repo.

My situation is that I am a novice at Svelte, D3 and Javascript in general; I come from a data science background, but am excited to learn all three by doing a little data visualization project. Your talk and your code have been instrumental to help me get some inkling of an idea about how D3 and Svelte play together; however since I am such a beginner, I would hoping for a more detailed explanation of how these two technologies could and should be combined.

If I understand it correctly, there are a handful of decisions one needs to make when deciding on how to combine these technologies. The main decisions amount to **how to divide the following responsibilities between D3 and Svelte:**
 1. **Lifecycle** management 
 2. **Styling** and layout
 3. **Animation** with emphasis on JS vs CSS approaches

Your talk touched on these, and in particular some remarks you made indicated some opinions especially on 2 and 3. Point 1 is a big challenge for me, as I don't have a completely clear understanding of the the individual lifecycles of either framework, let alone of them combine.

My request is whether you could consider writing an article that elaborates your take on how to combine D3 and Svelte is more explicit detail. It could look something like this:
  1. **Explanation:** how Svelte and D3 handle lifecycle, styling and animation (quick intro)
  2. **Comparison:** what are the strengths and weaknesses of D3 and Svelte (in summary)
  3. **Integration:** what are the strategies for combining the two, and which do you advocate (main section)

For a good example of this kind of article, but focusing on the lifecycle issues only, [see this article about integrating React and D3 lifecycles](https://www.smashingmagazine.com/2018/02/react-d3-ecosystem/).

If an article doesn't fit on your current schedule, a quick reply on this issue would already help me enormously.

I know this is a big ask, so here is a motivator for the full article: I think many data scientists and researchers face the challenge of _how to enter the world of interactive data visualization_. I believe that with a good guide, Svelte and D3 could be a nice way to introduce the data crowd to the Javascript world, and you may be one of the most qualified people in the world to do this, and improve that learning curve significantly.

Either way, thank you for your work! Your talk and your code have been inspirational.

Sincerely,
Matan

**Comment by higsch** [comment]
Hi Matan,

thanks a lot for opening this issue and your words!

You are correct that these are the decisions to take when using both Svelte and D3. In fact, I am planning to publish an article / blog post about one of my projects where I try to reveal how I go through this design process. There is no classical way how you would approach this and it depends also a lot on your data.

I will keep you and the community updated here. Until then, I can give you at least one advice and two useful links:
1. Try to handle as much as possible within Svelte and only, if you run in difficulties consult D3.
2. Have a look at [Layercake](https://layercake.graphics) and [Pancake](https://pancake-charts.surge.sh).

Best
Matthias

**Comment by ixxie** [comment]
Thanks for the tips Matthias! I guess I can get quite far with Layercake/Pancake. I look forward to your article.
